# Generated by Django 5.2.17 on 2026-09-09 02:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('contacto_nombre', models.CharField(max_length=120)),
                ('contacto_whatsapp', models.CharField(max_length=32)),
                ('meta_page_id', models.CharField(max_length=64, unique=True)),
                ('meta_form_id', models.CharField(max_length=64)),
                ('whatsapp_phone_number_id', models.CharField(max_length=64, unique=True)),
                ('whatsapp_template_inicial', models.CharField(default='umbral_bienvenida', max_length=128)),
                ('zonas_cobertura', models.JSONField(default=list)),
                ('tipos_obra_aceptados', models.JSONField(default=list)),
                ('presupuesto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('moneda', models.CharField(default='ARS', max_length=3)),
                ('calendar_id', models.CharField(blank=True, max_length=255)),
                ('duracion_visita_minutos', models.PositiveIntegerField(default=60)),
                ('horarios_visita', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('meta_lead_ad', 'Meta Lead Ad'), ('whatsapp', 'WhatsApp'), ('manual', 'Manual')], max_length=32)),
                ('meta_lead_id', models.CharField(blank=True, max_length=64, null=True)),
                ('nombre', models.CharField(blank=True, max_length=160)),
                ('telefono_e164', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('consentimiento_whatsapp', models.BooleanField(default=False)),
                ('payload_origen', models.JSONField(default=dict)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('calificando', 'Calificando'), ('calificado', 'Calificado'), ('no_calificado', 'No calificado'), ('requiere_humano', 'Requiere humano'), ('visita_agendada', 'Visita agendada'), ('visita_asistida', 'Visita asistida'), ('perdido', 'Perdido')], default='nuevo', max_length=32)),
                ('zona', models.CharField(blank=True, max_length=120)),
                ('tipo_obra', models.CharField(default='desconocido', max_length=32)),
                ('descripcion_obra', models.TextField(blank=True)),
                ('medidas_aproximadas', models.TextField(blank=True)),
                ('fotos', models.JSONField(blank=True, default=list)),
                ('rango_presupuesto', models.CharField(default='desconocido', max_length=24)),
                ('plazo', models.CharField(default='desconocido', max_length=24)),
                ('campos_faltantes', models.JSONField(blank=True, default=list)),
                ('motivos_calificacion', models.JSONField(blank=True, default=list)),
                ('resumen_ia', models.TextField(blank=True)),
                ('proxima_accion', models.CharField(default='preguntar', max_length=32)),
                ('visita_agendada_para', models.DateTimeField(blank=True, null=True)),
                ('visita_asistida_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direccion', models.CharField(choices=[('entrante', 'Entrante'), ('saliente', 'Saliente')], max_length=16)),
                ('canal', models.CharField(default='whatsapp', max_length=16)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('imagen', 'Imagen'), ('template', 'Template'), ('sistema', 'Sistema')], max_length=16)),
                ('texto', models.TextField(blank=True)),
                ('media', models.JSONField(blank=True, default=dict)),
                ('meta_message_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('estado_envio', models.CharField(choices=[('recibido', 'Recibido'), ('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído'), ('fallido', 'Fallido')], default='pendiente', max_length=16)),
                ('respuesta_ia', models.JSONField(blank=True, default=dict)),
                ('error_proveedor', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='core.lead')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('meta_lead_ads', 'Meta Lead Ads'), ('whatsapp', 'WhatsApp')], max_length=32)),
                ('external_event_id', models.CharField(max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='unique_provider_event')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['cliente', 'estado'], name='core_lead_cliente_90a18f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['telefono_e164'], name='core_lead_telefon_1ea308_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('cliente', 'meta_lead_id'), name='unique_meta_lead_per_cliente'),
        ),
    ]
