# Generated by Django 5.2.17 on 2026-09-09 14:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='manual_intake_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='meta_form_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='meta_page_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
