# Generated by Django 5.2.17 on 2026-09-10 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_manual_intake_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPiloto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('negocio', models.CharField(max_length=160)),
                ('telefono_e164', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('rubro', models.CharField(blank=True, max_length=64)),
                ('volumen_consultas', models.CharField(blank=True, max_length=32)),
                ('mensaje', models.TextField(blank=True)),
                ('consentimiento_contacto', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('contactada', 'Contactada'), ('calificada', 'Calificada'), ('descartada', 'Descartada')], default='nueva', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'solicitud de piloto',
                'verbose_name_plural': 'solicitudes de piloto',
                'ordering': ['-created_at'],
            },
        ),
    ]
